samples: ../conf/samples.tsv
units: ../conf/units.tsv
ped: ../conf/samples.ped
kits: ../resources/kits.tsv
internal_sid: "LIMS"

references:
    basepath: "/mnt/references"
    provider: "gatk"
    release: "hg38"

genome_fasta: "Homo_sapiens_assembly38.fasta"
refseq_intervals: "intervals/RefSeq_All_ncbiHg38_merged.bed"

known_variants:
    dbsnp: "Homo_sapiens_assembly38.dbsnp138.vcf"
    hapmap: "hapmap_3.3.hg38.vcf.gz"
    g1k: "1000G_phase1.snps.high_confidence.hg38.vcf.gz"
    omni: "1000G_omni2.5.hg38.vcf.gz"
    mills: "Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
    #ph1_indels: "known_variants/1000G_phase1.indels.hg19.sites.vcf"
    ph1_indels: "Homo_sapiens_assembly38.known_indels.vcf.gz"


tmp_dir: "/mnt/tmp"

rules:
    bwa_mem:
        arguments: "-M"
        platform: "illumina"
        threads: 6
    multiqc:
        arguments: "--force --cl_config 'picard_config: { general_stats_target_coverage: [10,20,30] }' --interactive --cl_config 'max_table_rows: 700'"
        threads: 12
    multiqc_heatmap:
        threads: 4
    trim_galore_pe:
        arguments: "-q 20 --fastqc --fastqc_args '--outdir qc/fastqc --quiet' --paired"
        threads: 8
    trim_galore_se:
        arguments: "-q 20 --fastqc --fastqc_args '--outdir qc/fastqc --quiet'"
        threads: 8
    picard_MarkDuplicates:
        arguments: "REMOVE_DUPLICATES=false ASSUME_SORTED=true CREATE_INDEX=true"
        threads: 6
    picard_pre_HsMetrics:
        threads: 1
    picard_HsMetrics:
        threads: 2
    picard_InsertSizeMetrics:
        threads: 2
    picard_WGSMetrics:
        arguments: "MINIMUM_MAPPING_QUALITY=-1 MINIMUM_BASE_QUALITY=-1 READ_LENGTH=150 COUNT_UNPAIRED=true"
    picard_gc_bias:
        params: ""
        threads: 8
    picard_mendelian_violations:
        threads: 6
    gatk_BQSR_data_processing:
        known_sites:
            - dbsnp
            - mills
            - ph1_indel
        threads: 6
    gatk_ApplyBQSR:
        threads: 6
    gatk_BQSR_quality_control:
        threads: 6
    gatk_HaplotypeCaller_ERC_GVCF:
        threads: 2
    gatk_GenomicsDBImport:
        db_suffix: "db_gatk"
        threads: 20
    gatk_GenotypeGVCFs:
        threads: 20
    gatk_VariantRecalibrator:
        threads: 20
    gatk_ApplyVQSR:
        threads: 20
    snpSift_caseControl_all:
        threads: 6
    samtools_sort:
        threads: 6
    samtools_merge:
        threads: 6
    samtools_cram_to_bam:
        threads: 6
    samtools_bam_to_cram:
        threads: 6
    samtools_index:
        threads: 1
    check_relationships:
        threads: 8
    freebayes_mtdna:
        threads: 6
    bedtools_coverage:
        params: ''
        sample_info: ''
        interval_target_list: "BED FILE WITH TARGET POSITIONS FOR COVERAGE CHECK"
